### ISSUE TITLE
train-all.R missing

### ISSUE THREAD

**Issue by nicornk** [fnoorian/geccoic15#1]
Hi Farzad,

while trying to reproduce your results, I wondered if you could upload the missing file `train-all.R`  which you describe in the Readme.

Thanks!

**Comment by fnoorian** [comment]
Hi Nicolas,

Thanks for noting this. I just added the file. See #f94ee40a0bc428d9d5d510c8a11d62932575ef1a
It calls all the different training subroutines in the training directory.

If you haven't seen it yet, the methodology was detailed in http://www.ee.usyd.edu.au/cel/UserFiles/File/Farzad/GECCO2015/gecco15_methodology_v2.pdf

Cheers!
